### ISSUE TITLE
itk_minc_nonlocal_filter --anlm: rician or gaussian model?

### ISSUE THREAD

**Issue by gdevenyi** [vfonov/patch_morphology#3]
I've been trying to dig through your code, but C++ is pretty rough to follow, I can't find where you implement your filter (or import ITK's)

Is the filter noise model gaussian or rician for this setting? Thanks.

**Comment by vfonov** [comment]
it's gaussian

the adaptative filter is implemented in https://github.com/vfonov/patch_morphology/blob/master/src/itk/itkVariableNoiseNonLocalFilter.h

**Comment by gdevenyi** [comment]
Ha cheers :) That looks nothing like C loops over voxels :)
